# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurements.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='measurements.proto',
  package='dfx.proto.measurements',
  syntax='proto3',
  serialized_pb=_b('\n\x12measurements.proto\x12\x16\x64\x66x.proto.measurements\"\xe2\x01\n\x0b\x44\x61taRequest\x12?\n\x06Params\x18\x01 \x01(\x0b\x32/.dfx.proto.measurements.DataRequest.ParamValues\x12\x0e\n\x06\x41\x63tion\x18\x02 \x01(\t\x12\x12\n\nChunkOrder\x18\x03 \x01(\r\x12\x11\n\tStartTime\x18\x04 \x01(\x04\x12\x0f\n\x07\x45ndTime\x18\x05 \x01(\x04\x12\x10\n\x08\x44uration\x18\x06 \x01(\x02\x12\x0f\n\x07Payload\x18\x07 \x01(\x0c\x12\x0c\n\x04Meta\x18\x08 \x01(\x0c\x1a\x19\n\x0bParamValues\x12\n\n\x02ID\x18\x01 \x01(\t\".\n\x0c\x44\x61taResponse\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x12\n\nChunkOrder\x18\x02 \x01(\r\"\x94\x01\n\x17SubscribeResultsRequest\x12K\n\x06Params\x18\x01 \x01(\x0b\x32;.dfx.proto.measurements.SubscribeResultsRequest.ParamValues\x12\x11\n\tRequestID\x18\x02 \x01(\t\x1a\x19\n\x0bParamValues\x12\n\n\x02ID\x18\x01 \x01(\t\"\x1a\n\x18SubscribeResultsResponse2\xd8\x01\n\x08Services\x12S\n\x04\x44\x61ta\x12#.dfx.proto.measurements.DataRequest\x1a$.dfx.proto.measurements.DataResponse\"\x00\x12w\n\x10SubscribeResults\x12/.dfx.proto.measurements.SubscribeResultsRequest\x1a\x30.dfx.proto.measurements.SubscribeResultsResponse\"\x00\x42#\n\x10\x61i.nuralogix.dfxB\x0cMeasurements\xf8\x01\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATAREQUEST_PARAMVALUES = _descriptor.Descriptor(
  name='ParamValues',
  full_name='dfx.proto.measurements.DataRequest.ParamValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='dfx.proto.measurements.DataRequest.ParamValues.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=273,
)

_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='dfx.proto.measurements.DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Params', full_name='dfx.proto.measurements.DataRequest.Params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Action', full_name='dfx.proto.measurements.DataRequest.Action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChunkOrder', full_name='dfx.proto.measurements.DataRequest.ChunkOrder', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='dfx.proto.measurements.DataRequest.StartTime', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EndTime', full_name='dfx.proto.measurements.DataRequest.EndTime', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='dfx.proto.measurements.DataRequest.Duration', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='dfx.proto.measurements.DataRequest.Payload', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Meta', full_name='dfx.proto.measurements.DataRequest.Meta', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAREQUEST_PARAMVALUES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=273,
)


_DATARESPONSE = _descriptor.Descriptor(
  name='DataResponse',
  full_name='dfx.proto.measurements.DataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='dfx.proto.measurements.DataResponse.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChunkOrder', full_name='dfx.proto.measurements.DataResponse.ChunkOrder', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=321,
)


_SUBSCRIBERESULTSREQUEST_PARAMVALUES = _descriptor.Descriptor(
  name='ParamValues',
  full_name='dfx.proto.measurements.SubscribeResultsRequest.ParamValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='dfx.proto.measurements.SubscribeResultsRequest.ParamValues.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=273,
)

_SUBSCRIBERESULTSREQUEST = _descriptor.Descriptor(
  name='SubscribeResultsRequest',
  full_name='dfx.proto.measurements.SubscribeResultsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Params', full_name='dfx.proto.measurements.SubscribeResultsRequest.Params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RequestID', full_name='dfx.proto.measurements.SubscribeResultsRequest.RequestID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SUBSCRIBERESULTSREQUEST_PARAMVALUES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=472,
)


_SUBSCRIBERESULTSRESPONSE = _descriptor.Descriptor(
  name='SubscribeResultsResponse',
  full_name='dfx.proto.measurements.SubscribeResultsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=500,
)

_DATAREQUEST_PARAMVALUES.containing_type = _DATAREQUEST
_DATAREQUEST.fields_by_name['Params'].message_type = _DATAREQUEST_PARAMVALUES
_SUBSCRIBERESULTSREQUEST_PARAMVALUES.containing_type = _SUBSCRIBERESULTSREQUEST
_SUBSCRIBERESULTSREQUEST.fields_by_name['Params'].message_type = _SUBSCRIBERESULTSREQUEST_PARAMVALUES
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['DataResponse'] = _DATARESPONSE
DESCRIPTOR.message_types_by_name['SubscribeResultsRequest'] = _SUBSCRIBERESULTSREQUEST
DESCRIPTOR.message_types_by_name['SubscribeResultsResponse'] = _SUBSCRIBERESULTSRESPONSE

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), dict(

  ParamValues = _reflection.GeneratedProtocolMessageType('ParamValues', (_message.Message,), dict(
    DESCRIPTOR = _DATAREQUEST_PARAMVALUES,
    __module__ = 'measurements_pb2'
    # @@protoc_insertion_point(class_scope:dfx.proto.measurements.DataRequest.ParamValues)
    ))
  ,
  DESCRIPTOR = _DATAREQUEST,
  __module__ = 'measurements_pb2'
  # @@protoc_insertion_point(class_scope:dfx.proto.measurements.DataRequest)
  ))
_sym_db.RegisterMessage(DataRequest)
_sym_db.RegisterMessage(DataRequest.ParamValues)

DataResponse = _reflection.GeneratedProtocolMessageType('DataResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATARESPONSE,
  __module__ = 'measurements_pb2'
  # @@protoc_insertion_point(class_scope:dfx.proto.measurements.DataResponse)
  ))
_sym_db.RegisterMessage(DataResponse)

SubscribeResultsRequest = _reflection.GeneratedProtocolMessageType('SubscribeResultsRequest', (_message.Message,), dict(

  ParamValues = _reflection.GeneratedProtocolMessageType('ParamValues', (_message.Message,), dict(
    DESCRIPTOR = _SUBSCRIBERESULTSREQUEST_PARAMVALUES,
    __module__ = 'measurements_pb2'
    # @@protoc_insertion_point(class_scope:dfx.proto.measurements.SubscribeResultsRequest.ParamValues)
    ))
  ,
  DESCRIPTOR = _SUBSCRIBERESULTSREQUEST,
  __module__ = 'measurements_pb2'
  # @@protoc_insertion_point(class_scope:dfx.proto.measurements.SubscribeResultsRequest)
  ))
_sym_db.RegisterMessage(SubscribeResultsRequest)
_sym_db.RegisterMessage(SubscribeResultsRequest.ParamValues)

SubscribeResultsResponse = _reflection.GeneratedProtocolMessageType('SubscribeResultsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBERESULTSRESPONSE,
  __module__ = 'measurements_pb2'
  # @@protoc_insertion_point(class_scope:dfx.proto.measurements.SubscribeResultsResponse)
  ))
_sym_db.RegisterMessage(SubscribeResultsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020ai.nuralogix.dfxB\014Measurements\370\001\001'))
# @@protoc_insertion_point(module_scope)
